// eslint-disable-next-line import/no-anonymous-default-export
export default {
  // Home
  IMAGE_SELECT: "Please choose an image",
  IMAGE_SELECT_BUTTON: "choose an image",
  WIDTH_BLOCK: "Number of horizontal blocks",
  CONVERT_BUTTON: "convert",
  IMAGE_DOWNLOAD: "Download image",
  CSV_DOWNLOAD: "Download csv",
  COMMAND_GENERATION: "Generate Command",
  EDIT: "Edit",
  REPLACE: "Replace",
  PREVIEW: "Preview",
  BACK_TO_HOME: "Back to home",
  JAVA_EDITION: "Java",
  BEDROCK_EDITION: "Bedrock",

  // Privacy
  PRIVACY_SECTION1: "The Service collects the following information",
  PRIVACY_SECTION2: "Purpose of using the information",
  PRIVACY_SECTION3: "Access Analysis Tools",
  PRIVACY_TEXT1:
    "Information about the OS and device, such as identification information generated using cookies, IDs generated by the OS, device type, and device identifier",
  PRIVACY_TEXT2:
    "To analyze the customer's activity history on the Service and use it to maintain and improve the Service.",
  PRIVACY_TEXT3:
    'This service uses "Google Analytics" to analyze your access to our website. Google Analytics uses cookies to collect traffic data. Traffic data is collected anonymously and does not personally identify you.',
  RETURN_HOME: "Return to home",
};
