/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandHelpIndexRouteImport } from './routes/command-help/index'
import { Route as CommandHelpJavaRouteImport } from './routes/command-help/java'
import { Route as CommandHelpBedrockIphoneRouteImport } from './routes/command-help/bedrock-iphone'
import { Route as CommandHelpBedrockRouteImport } from './routes/command-help/bedrock'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandHelpIndexRoute = CommandHelpIndexRouteImport.update({
  id: '/command-help/',
  path: '/command-help/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandHelpJavaRoute = CommandHelpJavaRouteImport.update({
  id: '/command-help/java',
  path: '/command-help/java',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandHelpBedrockIphoneRoute =
  CommandHelpBedrockIphoneRouteImport.update({
    id: '/command-help/bedrock-iphone',
    path: '/command-help/bedrock-iphone',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommandHelpBedrockRoute = CommandHelpBedrockRouteImport.update({
  id: '/command-help/bedrock',
  path: '/command-help/bedrock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/privacy': typeof PrivacyRoute
  '/command-help/bedrock': typeof CommandHelpBedrockRoute
  '/command-help/bedrock-iphone': typeof CommandHelpBedrockIphoneRoute
  '/command-help/java': typeof CommandHelpJavaRoute
  '/command-help/': typeof CommandHelpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/privacy': typeof PrivacyRoute
  '/command-help/bedrock': typeof CommandHelpBedrockRoute
  '/command-help/bedrock-iphone': typeof CommandHelpBedrockIphoneRoute
  '/command-help/java': typeof CommandHelpJavaRoute
  '/command-help': typeof CommandHelpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/privacy': typeof PrivacyRoute
  '/command-help/bedrock': typeof CommandHelpBedrockRoute
  '/command-help/bedrock-iphone': typeof CommandHelpBedrockIphoneRoute
  '/command-help/java': typeof CommandHelpJavaRoute
  '/command-help/': typeof CommandHelpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/privacy'
    | '/command-help/bedrock'
    | '/command-help/bedrock-iphone'
    | '/command-help/java'
    | '/command-help/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/privacy'
    | '/command-help/bedrock'
    | '/command-help/bedrock-iphone'
    | '/command-help/java'
    | '/command-help'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/privacy'
    | '/command-help/bedrock'
    | '/command-help/bedrock-iphone'
    | '/command-help/java'
    | '/command-help/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  PrivacyRoute: typeof PrivacyRoute
  CommandHelpBedrockRoute: typeof CommandHelpBedrockRoute
  CommandHelpBedrockIphoneRoute: typeof CommandHelpBedrockIphoneRoute
  CommandHelpJavaRoute: typeof CommandHelpJavaRoute
  CommandHelpIndexRoute: typeof CommandHelpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-help/': {
      id: '/command-help/'
      path: '/command-help'
      fullPath: '/command-help/'
      preLoaderRoute: typeof CommandHelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-help/java': {
      id: '/command-help/java'
      path: '/command-help/java'
      fullPath: '/command-help/java'
      preLoaderRoute: typeof CommandHelpJavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-help/bedrock-iphone': {
      id: '/command-help/bedrock-iphone'
      path: '/command-help/bedrock-iphone'
      fullPath: '/command-help/bedrock-iphone'
      preLoaderRoute: typeof CommandHelpBedrockIphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-help/bedrock': {
      id: '/command-help/bedrock'
      path: '/command-help/bedrock'
      fullPath: '/command-help/bedrock'
      preLoaderRoute: typeof CommandHelpBedrockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  PrivacyRoute: PrivacyRoute,
  CommandHelpBedrockRoute: CommandHelpBedrockRoute,
  CommandHelpBedrockIphoneRoute: CommandHelpBedrockIphoneRoute,
  CommandHelpJavaRoute: CommandHelpJavaRoute,
  CommandHelpIndexRoute: CommandHelpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
